name = "Custom Adventure 1.21.1"
author = "Aogami_JunJun"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2f44bbc2e1adb497f4dc44b5de529ca990c4314fc1e53dacaffc8e78778649fa"
