name = "Custom Adventure 1.21.1"
author = "Aogami_JunJun"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f9bcb9e286e6e3d446cc33ad18d14c93a38a609a77130ff53dbb17561bef19da"
